# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Bonelol
tagline:             'Every bone has its day!'
description:         ''
url:                 http://bonelol.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Max Meng
  url:               http://bonelol.github.io
  email:             gutoulol@gmail.com

# Custom vars
version:             1.0.0
